export const MOCK_PATIENT_OUTPUT = {
  patient_input: {
    cpt_code: "73721",
    zip_code: "06604",
    insurance_type: "aetna_ppo",
    provider_type: "hospital",
    urgency: "routine",
    deductible_status: "partially_met",
  },
  mode: "patient",
  cms_rates: {
    providers: [
      {
        provider_name: "Connecticut Advanced Imaging",
        provider_city: "Bridgeport",
        avg_submitted_chrg_amt: 1842.0,
        avg_medicare_allowed_amt: 466.3,
      },
      {
        provider_name: "St. Vincent's Medical Center",
        provider_city: "Bridgeport",
        avg_submitted_chrg_amt: 2310.0,
        avg_medicare_allowed_amt: 512.47,
      },
    ],
    min_rate: 466.3,
    max_rate: 512.47,
  },
  fee_schedule: {
    medicare_rate: 466.3,
    facility_fee: 198.42,
    non_facility_fee: 466.3,
    commercial_estimate_low: 746.08,
    commercial_estimate_mid: 885.97,
    commercial_estimate_high: 1025.86,
  },
  benefits: {
    deductible_remaining: 180.0,
    coinsurance: 0.2,
    prior_auth_required: true,
    prior_auth_notes: "Prior auth required for advanced imaging (MRI/CT/PET)",
    out_of_pocket_max: 6000.0,
    out_of_pocket_spent: 485.0,
    plan_name: "Aetna Open Access PPO",
    plan_type: "PPO",
  },
  cost_estimate: {
    total_low: 746,
    total_high: 1127,
    market_total_low: 746,
    market_total_high: 1127,
    oop_low: 293,
    oop_high: 370,
    insurance_low: 453,
    insurance_high: 757,
    explanation: "Demo explanation from stub.",
    savings_tips: [
      "Use an outpatient imaging center if in-network.",
      "Confirm prior authorization before booking.",
      "Bundle care inside one plan year when possible.",
    ],
  },
  ncci_result: {
    valid: true,
    edit_flags: [],
    mue_check: {},
  },
  denial_score: {
    risk_pct: 0.0,
    status: "LOW RISK",
    risk_factors: [],
    note_analysis: "",
  },
  fix_list: [],
  messages: [
    { role: "system", content: "Entry validation passed." },
    { role: "system", content: "NLP parser normalized patient input." },
    { role: "system", content: "Supervisor: routing to patient path." },
    { role: "system", content: "Coverage analyzer: demo stub." },
    { role: "system", content: "Predictor guard passed." },
    { role: "system", content: "Cost predictor: demo stub." },
    { role: "system", content: "Output normalized for UI." },
  ],
};

export const MOCK_HOSPITAL_OUTPUT = {
  hospital_input: {
    cpt_code: "73721",
    icd_code: "M17.11",
    payer: "aetna_ppo",
    clinical_note:
      "Patient with right knee pain for 3 months, positive McMurray test, medial compartment narrowing on X-ray. MRI requested to evaluate meniscal injury.",
  },
  mode: "hospital",
  benefits: {
    deductible_remaining: 180.0,
    coinsurance: 0.2,
    prior_auth_required: true,
    prior_auth_notes: "Prior auth required for advanced imaging (MRI/CT/PET)",
    out_of_pocket_max: 6000.0,
    out_of_pocket_spent: 485.0,
    plan_name: "Aetna Open Access PPO",
    plan_type: "PPO",
  },
  cost_estimate: {
    total_low: 0.0,
    total_high: 0.0,
    market_total_low: 0.0,
    market_total_high: 0.0,
    oop_low: 0.0,
    oop_high: 0.0,
    insurance_low: 0.0,
    insurance_high: 0.0,
  },
  ncci_result: {
    valid: true,
    edit_flags: [],
    mue_check: {},
  },
  denial_score: {
    risk_pct: 0.34,
    status: "HIGH RISK",
    risk_factors: [
      {
        factor_key: "missing_prior_auth",
        description: "Prior authorization not obtained or not on file",
        risk_increase: 0.3,
      },
    ],
    note_analysis: "Clinical note is likely adequate, but prior auth is missing.",
  },
  fix_list: [
    {
      issue: "Prior authorization not on file",
      action: "Contact payer and attach auth number in claim field 23.",
      risk_reduction: 0.28,
      applied: false,
    },
  ],
  messages: [
    { role: "system", content: "Entry validation passed." },
    { role: "system", content: "NLP parser normalized hospital input." },
    { role: "system", content: "Supervisor: routing to hospital path." },
    { role: "system", content: "Coverage analyzer: demo stub." },
    { role: "system", content: "Predictor guard passed." },
    { role: "system", content: "Denial predictor: demo stub." },
    { role: "system", content: "Output normalized for UI." },
  ],
};

export const MOCK_HOSPITAL_REEVAL_OUTPUT = {
  hospital_input: {
    cpt_code: "73721",
    icd_code: "M17.11",
    payer: "aetna_ppo",
    clinical_note:
      "Patient with right knee pain for 3 months, positive McMurray test, medial compartment narrowing on X-ray. MRI requested to evaluate meniscal injury.",
  },
  mode: "hospital",
  benefits: {
    deductible_remaining: 180.0,
    coinsurance: 0.2,
    prior_auth_required: true,
    prior_auth_notes: "Prior auth required for advanced imaging (MRI/CT/PET)",
    out_of_pocket_max: 6000.0,
    out_of_pocket_spent: 485.0,
    plan_name: "Aetna Open Access PPO",
    plan_type: "PPO",
  },
  cost_estimate: {
    total_low: 0.0,
    total_high: 0.0,
    market_total_low: 0.0,
    market_total_high: 0.0,
    oop_low: 0.0,
    oop_high: 0.0,
    insurance_low: 0.0,
    insurance_high: 0.0,
  },
  ncci_result: {
    valid: true,
    edit_flags: [],
    mue_check: {},
  },
  denial_score: {
    risk_pct: 0.04,
    status: "LOW RISK",
    risk_factors: [],
    note_analysis: "Prior auth attached. Low residual risk.",
  },
  fix_list: [
    {
      issue: "Prior authorization not on file",
      action: "Attach auth number in claim field 23.",
      risk_reduction: 0.28,
      applied: true,
    },
  ],
  messages: [
    { role: "system", content: "Entry validation passed." },
    { role: "system", content: "NLP parser normalized hospital input." },
    { role: "system", content: "Supervisor: routing to hospital path." },
    { role: "system", content: "Coverage analyzer: demo stub." },
    { role: "system", content: "Predictor guard passed." },
    { role: "system", content: "Denial predictor: re-eval stub." },
    { role: "system", content: "Output normalized for UI." },
  ],
  reeval: false,
};
